#+TITLE: dmscripts
#+AUTHOR: Derek Taylor (https://gitlab.com/dwt1/dmscripts)

* NAME
dmscripts - a collection of various dmenu scripts

* DESCRIPTION
dmscripts are a collection of dmenu scripts written in bash.  each script is written and contributed by DT or viewers.

* SCRIPTS
** dm-hub
The hub script, allows easy access to other scripts.
** dm-man
A manual page searcher, search a man page or randomly view one.
** dm-colpick
Find the hex value of a color you are searching for.
** dm-confedit
A configuration manager, find and edit any config file you need.
** dm-currencies
Convert prices between currencies.
** dm-ip
Get IP of interface or external IP
** dm-kill
Simple process killer, find and kill misbehaving processes.
** dm-logout
Simple logout menu, choose to lock, shutdown, reboot or logout of your computer.
** dm-music
Dmenu based music player.
** dm-note
Store multiple one-line texts or codes and copy one of them when needed.
** dm-bookman
A bookmark searching tool, search through all qutebrowser quickmarks and bookmarks.
** dm-record
Records audio, video and webcam.
** dm-reddit
A reddit viewer using dmenu, still a work in progress.
** dm-maim
A GUI to maim using dmenu.
** dm-websearch
Web searching utility using dmenu.
** dm-weather
Simple graphical weather app
** dm-sounds
Choose an ambient background sound to play.
** dm-translate
Translate using Google Translate (through Lingva Translate)
** dm-usbmount
USB mounting done suckless, no need for bloated daemons.
** dm-setbg
Using dmenu, setup a wallpaper.
** dm-wifi
Connect to wifi using dmenu.
** dm-youtube
Youtube subscriptions without an account or the API tying you down.
** _dm-helper.sh
Helper scripts adding functionality to other scripts

* USAGE
** bash dm-hub
Runs the dm-hub program which allows for easy access to the scripts.
** bash path/to/script
Runs the script specified without using dmhub.
** ./path/to/script
Same as bash path/to/script.

* AUTHOR
Derek Taylor (https://gitlab.com/dwt1/dmscripts)
