#!/usr/bin/env bash
#
# Script name: dmsetup
# Description: Downloads all the requried dependencies for all the scripts and copys the scripts to a folder of your choice and makes all the scripts executable
# Dependencies: dmenu, A-package-manager if yours is not listed please add it. 
# GitLab: https://www.gitlab.com/dwt1/setup
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: n-e0

package-names () {
    echo xclip
    echo xargs
    echo systemd
    echo slock
    echo notify-send
    echo qutebrowser
    echo reddio
    echo zenity
    echo maim
#    echo teeto
    echo xdotool
    echo xrandr
}

pacman-install () {      
    echo "installing"
    sudo pacman -S xclip
    sudo pacman -S findutils
    sudo pacman -S slock
    sudo pacman -S libnotify
    sudo pacman -S qutebrowser
    yay -S reddio
    sudo pacman -S zenity
    sudo pacman -S maim
    sudo pacman -S xdotool
    sudo pacman -S xorg-xrandr
    echo "done installing"
    make-executable
}

apt-install () {
    echo "installing"
	sudo apt install xclip > /dev/null 2>&1
    sudo apt install systemd > /dev/null 2>&1
    sudo apt install slock > /dev/null 2>&1
    sudo apt install notify-send > /dev/null 2>&1
    sudo apt install qutebrowser > /dev/null 2>&1
    #sudo apt install reddio > /dev/null 2>&1
    sudo apt install zenity > /dev/null 2>&1
    sudo apt install maim > /dev/null 2>&1
    sudo apt install xdotool > /dev/null 2>&1
    sudo apt install x11-xserver-utils > /dev/null 2>&1
    echo "done installing"
    make-executable
}


declare -a yesno=(
    "Yes"
    "No"
)

declare -a packageman=(
    "Pacman"
    "Apt"
    "Quit"
)

declare -a pathexample=(
    "eg. /home/user/dmscripts"
)

choice=$(printf '%s\n' "${packageman[@]}" | dmenu -i -p 'Package Manager:' "$@")
scriptpath="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

check-path () {
    path=$(printf '%s\n' "${pathexample[@]}" | dmenu -i -p 'Enter Path To scripts directory:' "$@")
    doespathexist=false
    if [ -e $path/dman ] ; then
        ls > /dev/null
    else
        confirm=$(printf '%s\n' "${yesno[@]}" | dmenu -i -p "Creating directory at $path are you sure?:" "$@")
        case "$confirm" in
            'Yes')
                mkdir $path
                cp "$scriptpath"/* "$path"

            ;;
            'No')
                check-path

            ;;
            *)
                check-path
            ;;
        esac
    fi
}

make-executable () {
    chmod 755 $path
    echo "scripts in $path are executable"
}

main () {

    check-path

    case "$choice" in

	'Pacman')
        pacman-install
        
    ;;
    'Apt')
        apt-install
        
    ;;
    'Quit')
        echo "Program terminated." && exit 0
    ;;
    *)
        exit 0
    ;;
    esac
}

main
