#!/usr/bin/env bash
#
# Script name: dmpower
# Description: Dmenu as a reddit viewer using reddio.
# Dependencies: dmenu, reddio, zenity
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor

# An array of subreddits to choose.
declare -a subreddit_list=(
"r/archlinux"
"r/bash"
"r/commandline"
"r/emacs"
"r/freesoftware"
"r/linux"
"r/linux4noobs"
"r/linuxmasterrace"
"r/linuxquestions"
"r/suckless"
"r/Ubuntu"
"r/unixporn"
"r/vim"
"Quit"
)
# Picking a subreddit from the above subreddit_list.
while [ -z "$subreddit" ]; do
    subreddit=$(printf '%s\n' "${subreddit_list[@]}" | dmenu -i -l 20 -p "Choose a subreddit:" "$@") || exit
done

# Show the last 20 posts (titles and ids) from the chosen subreddit.
# NOTE: I use 'bash reddio ...' for the reddio commands because reddio uses /bin/sh
# in its shebang, which would cause fish shell users some problems.
while [ -z "$post_title" ]; do
    post_title=$(bash reddio print -f '$num. $title $id$nl' -l 20 "$subreddit" | \
    dmenu -i -l 20 -p 'Last 20 posts on '"$subreddit" "$@") || exit
done

# Display contents of chosen post in a zenity text box.
if [ -z "$read_post" ]; then
    post_id=$(printf '%s\n' "$post_title" | awk '{print $NF}')
    read_post=$(bash reddio print -f ' TITLE: $title$nl SUBMITTED: $created_pretty$nl AUTHOR: $author$nl$nl$text' by_id/"$post_id" | \
              zenity --text-info --height=600 --width=600) || exit
fi
