#!/usr/bin/env bash
#
# Script name: dmscrot
# Description: Choose type of screenshot to take with maim.
# Dependencies: dmenu, maim, tee, xdotool, xclip
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Simon Ingelsson
#               Steven Hall

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# Specifying a directory to save our screenshots.
SCROTDIR="$HOME/Screenshots"
# Makes sure the directory exists.
mkdir -p "${SCROTDIR}"

getStamp() {
  date '+%Y%m%d-%H%M%S'
}

MAIM_ARGS=""
MAIM_FILE=""

# Get monitors and their settings for maim
DISPLAYS=$(xrandr --listactivemonitors | grep '+' | awk '{print $4, $3}' | awk -F'[x/+* ]' '{print $1,$2"x"$4"+"$6"+"$7}')

# What modes do we have
declare -a modes=(
"Fullscreen"
"Active window"
"Selected region"
)

# Add monitor data
IFS=$'\n'
declare -A DISP
for i in ${DISPLAYS}; do
  name=$(echo "${i}" | awk '{print $1}')
  rest="$(echo "${i}" | awk '{print $2}')"
  modes[${#modes[@]}]="${name}"
  DISP[${name}]="${rest}"
done
unset IFS

target=$(printf '%s\n' "${modes[@]}" | dmenu -i -l 20 -p 'Take screenshot of:') || exit 1
case "$target" in
  'Fullscreen')
    MAIM_ARGS=""
    MAIM_FILE="${SCROTDIR}/scrot-full-$(getStamp).png"
  ;;
  'Active window')
    active_window=$(xdotool getactivewindow)
    MAIM_ARGS="-i ${active_window}"
    MAIM_FILE="${SCROTDIR}/scrot-window-$(getStamp).png"
  ;;
  'Selected region')
    MAIM_ARGS="-s"
    MAIM_FILE="${SCROTDIR}/scrot-region-$(getStamp).png"
  ;;
  *)
    MAIM_ARGS="-g ${DISP[${target}]}"
    MAIM_FILE="${SCROTDIR}/scrot-${target}-$(getStamp).png"
  ;;
esac

declare -a destination=( "File" "Clipboard" "Both" )
dest=$(printf '%s\n' "${destination[@]}" | dmenu -i -l 20 -p 'Destination:') || exit 1
case "$dest" in
  'File')
    maim ${MAIM_ARGS} "${MAIM_FILE}"
  ;;
  'Clipboard')
    maim ${MAIM_ARGS} | xclip -selection clipboard -t image/png
  ;;
  'Both')
    maim ${MAIM_ARGS} | tee "${MAIM_FILE}" | xclip -selection clipboard -t image/png
  ;;
  *)
    exit 1
  ;;
esac

exit 0
