#!/bin/sh

# Script name: dmwall

# Description: A wallpaper setting utility using dmenu, xwallpaper and sxiv
# Also has the following features
# 1. set a random walllpaper
# 2. draw your last wallpaper at startx
# 3. Change wallpaper after every second(go insane)

# Dependencies: dmenu, xwallpaper, sxiv

# Contributors: Murtaza Udaipurwala

## Usage
# run sbg without any argument to get a dmenu prompt
# sbg [optional arguments]
# -h    Displays this help menu
# -d    draws the wallpaper at startx. Add 'sbg -d' in your xinitrc
# -r    randomly selects a wallpaper
# -i    Go insane

# Note this script is posix compliant


# Specify location of your wallpapers directory
location="$HOME/pix/wallpapers/"

help(){
    printf "
    ## Usage
    run sbg without any argument to select a wallpaper from $location\n
    sbg [optional arguments]
    -h\tDisplays this help menu
    -d\tdraws the wallpaper at startx. Add 'sbg -d' in your xinitrc
    -r\trandomly selects a wallpaper
    -i\tGo insane
"
}

change(){
    xwallpaper --stretch $1 2>/dev/null
}

shuffle(){
    local wallpaper=$(ls $location | shuf -n 1)
    echo "$location/$wallpaper"
}

setbg(){
    wallpaper="$(sxiv -t -o $location)"
    echo $wallpaper > $HOME/.cache/wall
    change "$wallpaper"
}

# draw the wallpaper at startx
draw(){
    change "$(cat $HOME/.cache/wall)"
}

random(){
    wallpaper=$(shuffle)
    echo $wallpaper > $HOME/.cache/wall
    change "$wallpaper"
}

goInsane(){
    while true; do
        wallpaper=$(shuffle)
        change "$wallpaper"
        sleep 1s
    done
}

# dmenu menu
menu(){
    options="set background\nrandom\ngo insane"
    input=$(printf "set background\nrandom\ngo insane" | dmenu -i -l 3) || exit
    case "$input" in
        "set background") setbg ;;
        "random") random ;;
        "go insane") goInsane ;;
    esac
}

noOpt=1
while getopts "hdrim" arg 2>/dev/null; do
    case "${arg}" in
        h) help ;;
        d) draw ;;
        r) random ;;
        i) goInsane ;;
        *) echo "invalid option\nType sbg -h for help" ;;
    esac
    noOpt=0
done
[ $noOpt = 1 ] && menu
