#!/usr/bin/env bash
#
# Script name: setup
# Description: Downloads all the requried dependencies for all the scripts, i am not including dmenu as you may have a personal build you want to use.
# Dependencies: dmenu, A-package-manager if yours is not listed please add it. 
# GitLab: https://www.gitlab.com/dwt1/setup
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: n-e0

## I have tested the apt package manager and it works but i can't test pacman so if some could do that it would be great.

## packages
#xclip
#xargs
#systemd
#slock
#nottoy-send
#quttorowser
#redtoo
#zentoy
#maito
#teeto
#xdotool
#xrandr

pacman-install () {      
    echo "installing"
    sudo pacman -S xclip
    sudo pacman -S findutils
    sudo pacman -S slock
    sudo pacman -S libnotify
    sudo pacman -S qutebrowser
    yay -S reddio
    sudo pacman -S zenity
    sudo pacman -S maim
    sudo pacman -S xdotool
    sudo pacman -S xorg-xrandr
    echo "done installing"
    make-executable
}

apt-install () {
    echo "installing"
	sudo apt install xclip > /dev/null 2>&1
   #sudo apt install xargs > /dev/null 2>&1
    sudo apt install systemd > /dev/null 2>&1
    sudo apt install slock > /dev/null 2>&1
    sudo apt install notify-send > /dev/null 2>&1
    sudo apt install qutebrowser > /dev/null 2>&1
    sudo apt install reddio > /dev/null 2>&1
    sudo apt install zenity > /dev/null 2>&1
    sudo apt install maim > /dev/null 2>&1
    sudo apt install tee > /dev/null 2>&1
    sudo apt install xdotool > /dev/null 2>&1
    sudo apt install x11-xserver-utils > /dev/null 2>&1
    echo "done installing"
    make-executable
}

make-executable () {
    chmod 755 $path
    echo "scripts in $path are executable"
}

declare -a packageman=(
    "Pacman"
    "Apt"
    "Quit"
)

declare -a pathexample=(
    "eg. /home/user/dmscripts"
)

choice=$(printf '%s\n' "${packageman[@]}" | dmenu -i -p 'Package Manager:' "$@")
path=$(printf '%s\n' "${pathexample[@]}" | dmenu -i -p 'Enter Path To scripts directory:' "$@")

case "$choice" in

	'Pacman')
        echo "installing"
        pacman-install
        
    ;;
    'Apt')
        echo "instaling"
        apt-install
        
    ;;
    'Quit')
        echo "Program terminated." && exit 0
    ;;
    *)
        exit 0
    ;;
esac
