#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# To edit this file copy it to `${HOME}/.config/dmscripts/config`
# `cp /etc/dmscripts/config ${HOME}/.config/dmscripts/config`

# Defined variables, modify anything in quotes to your prefered software

DMENU="dmenu"
# DMENU="rofi -dmenu"

DMBROWSER="brave"
# DMBROWSER="qutebrowser"

DMTERM="st -e"
# DMTERM="alacritty -e"

DMEDITOR="emacsclient -c -a emacs"
# DMEDITOR="${DMTERM} vim"

# dm-logout
logout_locker='slock'
# logout_locker='dm-tool lock'

# dm-bookman 
bookman_show_source=1

# dm-sounds
sounds_dir="${HOME}/.config/dmscripts/dmsounds"

# dm-setbg
setbg_dir="${HOME}/Pictures/Wallpapers"

# dm-maim
maim_dir="${HOME}/Screenshots"
maim_file_prefix="maim"

# dm-confedit
confedit_editor="$DMEDITOR"
declare -A confedit_list
confedit_list[confedit]="$HOME/.config/dmscripts/config"
confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.yml"
confedit_list[awesome]="$HOME/.config/awesome/rc.lua"
confedit_list[bash]="$HOME/.bashrc"
confedit_list[broot]="$HOME/.config/broot/conf.toml"
confedit_list[bspwm]="$HOME/.config/bspwm/bspwmrc"
confedit_list[doom emacs config.el]="$HOME/.config/doom/config.el"
confedit_list[doom emacs config.org]="$HOME/.config/doom/config.org"
confedit_list[doom emacs init.el]="$HOME/.config/doom/init.el"
confedit_list[doom emacs packages.el]="$HOME/.config/doom/packages.el"
confedit_list[dunst]="$HOME/.config/dunst/dunstrc"
confedit_list[dwm]="$HOME/dwm-distrotube/config.def.h"
confedit_list[dwmblocks]="$HOME/dwmblocks-distrotube/blocks.def.h"
confedit_list[fish]="$HOME/.config/fish/config.fish"
confedit_list[herbstluftwm]="$HOME/.config/herbstluftwm/autostart"
confedit_list[i3]="$HOME/.config/i3/config"
confedit_list[ncmpcpp]="$HOME/.config/ncmpcpp/config"
confedit_list[neovim]="$HOME/.config/nvim/init.vim"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[polybar]="$HOME/.config/polybar/config"
confedit_list[qtile]="$HOME/.config/qtile/config.py"
confedit_list[qutebrowser bookmarks]="$HOME/.config/qutebrowser/bookmarks/urls"
confedit_list[qutebrowser quickmarks]="$HOME/.config/qutebrowser/quickmarks"
confedit_list[qutebrowser config.py]="$HOME/.config/qutebrowser/config.py"
confedit_list[spectrwm]="$HOME/.spectrwm.conf"
confedit_list[ssh]="$HOME/.ssh/config"
confedit_list[st]="$HOME/st-distrotube/config.def.h"
confedit_list[stumpwm]="$HOME/.config/stumpwm/config"
confedit_list[surf]="$HOME/surf-distrotube/config.def.h"
confedit_list[sxhkd]="$HOME/.config/sxhkd/sxhkdrc"
confedit_list[tabbed]="$HOME/tabbed-distrotube/config.def.h"
confedit_list[vifm]="$HOME/.config/vifm/vifmrc"
confedit_list[vim]="$HOME/.vimrc"
confedit_list[xmobar mon1]="$HOME/.config/xmobar/xmobarrc0"
confedit_list[xmobar mon2]="$HOME/.config/xmobar/xmobarrc1"
confedit_list[xmobar mon3]="$HOME/.config/xmobar/xmobarrc2"
confedit_list[xmonad]="$HOME/.xmonad/README.org"
confedit_list[xinitrc]="$HOME/.xinitrc"
confedit_list[xresources]="$HOME/.Xresources"
confedit_list[zsh]="$HOME/.zshrc"

# dm-reddit config
declare -a reddit_list=(
"r/archlinux"
"r/bash"
"r/commandline"
"r/emacs"
"r/freesoftware"
"r/linux"
"r/linux4noobs"
"r/linuxmasterrace"
"r/linuxquestions"
"r/suckless"
"r/Ubuntu"
"r/unixporn"
"r/vim"
)

# Search engine config 
websearch_browser="$DMBROWSER"
declare -A websearch
# Syntax:
# websearch[name]="https://www.example.com/search?q="

# Search Engines
websearch[bing]="https://www.bing.com/search?q="
websearch[brave]="https://search.brave.com/search?q="
websearch[duckduckgo]="https://duckduckgo.com/?q="
websearch[gemini search \(https\)]="https://portal.mozz.us/gemini/geminispace.info/search%3F"
websearch[google]="https://www.google.com/search?q="
websearch[qwant]="https://www.qwant.com/?q="
websearch[swisscows]="https://swisscows.com/web?query="
websearch[yandex]="https://yandex.com/search/?text="
# Information/News
websearch[bbcnews]="https://www.bbc.co.uk/search?q="
websearch[cnn]="https://www.cnn.com/search?q="
websearch[googlenews]="https://news.google.com/search?q="
websearch[wikipedia]="https://en.wikipedia.org/w/index.php?search="
websearch[wiktionary]="https://en.wiktionary.org/w/index.php?search="
# Social Media
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[odysee]="https://odysee.com/$/search?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
# Online Shopping
websearch[amazon]="https://www.amazon.com/s?k="
websearch[craigslist]="https://www.craigslist.org/search/sss?query="
websearch[ebay]="https://www.ebay.com/sch/i.html?&_nkw="
websearch[gumtree]="https://www.gumtree.com/search?search_category=all&q="
# Linux
websearch[archaur]="https://aur.archlinux.org/packages/?O=0&K="
websearch[archpkg]="https://archlinux.org/packages/?sort=&q="
websearch[archwiki]="https://wiki.archlinux.org/index.php?search="
websearch[debianpkg]="https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords="
# Development
websearch[github]="https://github.com/search?q="
websearch[gitlab]="https://gitlab.com/search?search="
websearch[googleOpenSource]="https://opensource.google/projects/search?q="
websearch[sourceforge]="https://sourceforge.net/directory/?q="
websearch[stackoverflow]="https://stackoverflow.com/search?q="
# Etc

# dm-youtube config
youtube_browser="$DMBROWSER"
# Think of these as your "subscribed channels", name the channel in the square brackets then put the channel URL in the quotation marks
# Syntax: youtube_channels[name]="https://www.youtube.com/link/to/channel"

declare -A youtube_channels
youtube_channels[distrotube]="https://www.youtube.com/c/DistroTube/featured"

# dm-colpick config
declare -A colpick_list
colpick_list[black]="#282a36"
colpick_list[red]="#ff5555"
colpick_list[green]="#5af78e"
colpick_list[yellow]="#f1fa8c"
colpick_list[blue]="#57c7ff"
colpick_list[magenta]="#ff6ac1"
colpick_list[cyan]="#8be9fd"
colpick_list[white]="#f1f1f0"
colpick_list[orange]="#ffb86c"
colpick_list[purple]="#bd9cf9"

_revision=13

# dm-translate
declare -A translate_list
translate_list[autodetect]="auto"
translate_list[afrikaans]="af"
translate_list[albanian]="sq"
translate_list[amharic]="am"
translate_list[arabic]="ar"
translate_list[armenian]="hy"
translate_list[azerbaijani]="az"
translate_list[basque]="eu"
translate_list[belarusian]="be"
translate_list[bengali]="bn"
translate_list[bosnian]="bs"
translate_list[bulgarian]="bg"
translate_list[catalan]="ca"
translate_list[cebuano]="ceb"
translate_list[chichewa]="ny"
translate_list[chinese]="zh-CN"
translate_list[corsican]="co"
translate_list[croatian]="hr"
translate_list[czech]="cs"
translate_list[danish]="da"
translate_list[dutch]="nl"
translate_list[english]="en"
translate_list[esperanto]="eo"
translate_list[estonian]="et"
translate_list[filipino]="tl"
translate_list[finnish]="fi"
translate_list[french]="fr"
translate_list[frisian]="fy"
translate_list[galician]="gl"
translate_list[georgian]="ka"
translate_list[german]="de"
translate_list[greek]="el"
translate_list[gujarati]="gu"
translate_list[haitian creole]="ht"
translate_list[hausa]="ha"
translate_list[hawaiian]="haw"
translate_list[hebrew]="iw"
translate_list[hindi]="hi"
translate_list[hmong]="hmn"
translate_list[hungarian]="hu"
translate_list[icelandic]="is"
translate_list[igbo]="ig"
translate_list[indonesian]="id"
translate_list[irish]="ga"
translate_list[italian]="it"
translate_list[japanese]="ja"
translate_list[javanese]="jw"
translate_list[kannada]="kn"
translate_list[kazakh]="kk"
translate_list[khmer]="km"
translate_list[kinyarwanda]="rw"
translate_list[korean]="ko"
translate_list[kurdish (kurmanji)]="ku"
translate_list[kyrgyz]="ky"
translate_list[lao]="lo"
translate_list[latin]="la"
translate_list[latvian]="lv"
translate_list[lithuanian]="lt"
translate_list[luxembourgish]="lb"
translate_list[macedonian]="mk"
translate_list[malagasy]="mg"
translate_list[malay]="ms"
translate_list[malayalam]="ml"
translate_list[maltese]="mt"
translate_list[maori]="mi"
translate_list[marathi]="mr"
translate_list[mongolian]="mn"
translate_list[myanmar (burmese)]="my"
translate_list[nepali]="ne"
translate_list[norwegian]="no"
translate_list[odia (oriya)]="or"
translate_list[pashto]="ps"
translate_list[persian]="fa"
translate_list[polish]="pl"
translate_list[portuguese]="pt"
translate_list[punjabi]="pa"
translate_list[romanian]="ro"
translate_list[russian]="ru"
translate_list[samoan]="sm"
translate_list[scots gaelic]="gd"
translate_list[serbian]="sr"
translate_list[sesotho]="st"
translate_list[shona]="sn"
translate_list[sindhi]="sd"
translate_list[sinhala]="si"
translate_list[slovak]="sk"
translate_list[slovenian]="sl"
translate_list[somali]="so"
translate_list[spanish]="es"
translate_list[sundanese]="su"
translate_list[swahili]="sw"
translate_list[swedish]="sv"
translate_list[tajik]="tg"
translate_list[tamil]="ta"
translate_list[tatar]="tt"
translate_list[telugu]="te"
translate_list[thai]="th"
translate_list[turkish]="tr"
translate_list[turkmen]="tk"
translate_list[ukrainian]="uk"
translate_list[urdu]="ur"
translate_list[uyghur]="ug"
translate_list[uzbek]="uz"
translate_list[vietnamese]="vi"
translate_list[welsh]="cy"
translate_list[xhosa]="xh"
translate_list[yiddish]="yi"
translate_list[yoruba]="yo"
translate_list[zulu]="zu"
