#!/usr/bin/env bash
#
# Script name: dmcolors
# Description: Copy a color to your clipboard using dmenu, change the colors if needed
# Dependencies: dmenu, xclip
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: sloopy3333
#               Simon Ingelsson
#               HostGrady

# Set with the flags "-e", "-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"


# As this is loaded from other file it is technically not defined
# shellcheck disable=SC2154
selected="$(printf '%s\n' "${!colors[@]}" | dmenu -p "color:" "$@")"
[ -z "${selected}" ] && exit
echo "${colors["${selected}"]}" | xclip -r -selection clipboard

