#!/usr/bin/env bash
#
# Script name: dm-hub
# Description: A hub that you can execute all the other scripts from.
# Dependencies: dmenu, executable dmscripts, all the dependancies from dmscripts
# GitLab: https://www.gitlab.com/dwt1/hub
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: n-e0
#               Simon Ingelsson

set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

# Listings will be in format: "filename - the description pulled from the header of the script."
# This is done with awk (based on colons).
listings=$(grep -r '^# Description: ' $(find "${_path}" -type f -name "dm-*") | awk -F ':' '{print $1 " -" $3}' | cut -d / -f3-)

# Declaring "listings" as an array
declare -a listings

# Piping "listings" into awk to get the filename without path (based on slashes).
# Then sorting.  Then piping everything into dmenu.
choice=$(printf '%s\n' "${listings[@]}" | awk -F '/'  '{print $NF}' | sort | ${DMENU} 'Run Script:' "$@")

# If we select a "choice" then we execute: bash name-of-file
# We get name-of-file without the description with awk (based on dashes).
if [ "${choice}" ]; then
    bash "$(printf '%s\n' "${choice}" | awk -F ' - ' '{print $1}')" "$@"
else
    echo "Program terminated." && exit 0
fi

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
