#!/usr/bin/env bash

# script name: dm-pacman
# Description: A software manager using dmenu
# Dependencies: dmenu, pacman
# Contributors: Murtaza Udaipurwala
#               HostGrady
#               Simon Ingelsson
#

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

refresh(){
    # only update the packageList once a day
    [ "$(stat -c %y "$packageList" 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
        pacman -Si \
        | awk '/^Name/{name=$3} /^Description/{sub(/^.{18}/,"", $0); print name, " => ", $0}' > "${packageList}"
}

confirm(){
    answer=$(printf "No\nYes" | dmenu -i -p "$1") || exit
    [ "$answer" = "No" ] && exit
}

install(){
    refresh
    package=$(dmenu -i -l 30 -p "Package to install" < "$packageList") || exit
    confirm "Install this package?"
    $DMTERM sudo pacman -S --noconfirm "$(echo "$package" | cut -d'=' -f1)"
}

remove(){
    package=$(pacman -Qeq | dmenu -i -l 30 -p "Package to remove") || exit
    confirm "Remove this package?"
    $DMTERM sudo pacman -Rns --noconfirm "$package"
}

update(){
    confirm "Update the system?"
    $DMTERM sudo pacman -Syu --noconfirm
}

cleanUp(){
    [ "$(pacman -Qdtq)" = "" ] && exit
    $DMTERM sudo pacman -Rns --noconfirm "$(pacman -Qdtq)"
}

menu(){
    operation=$(printf "install\nremove\nupdate\nremove orphan packages" | dmenu -i -l 4 -p "Select operation" "${@}") || exit
    case $operation in
        "install") install ;;
        "remove") remove ;;
        "update") update ;;
        "remove orphan packages") cleanUp ;;
        *) echo "invalid operation" && exit ;;
    esac
}


packageList="$HOME/.cache/packageList"

menu "${@}"
