#!/usr/bin/env bash
#
# Script name: dmred
# Description: Dmenu as a reddit viewer using reddio.
# Dependencies: dmenu, reddio, zenity
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               HostGrady
#               Simon Ingelsson

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

function get_config() {
  local loaded=0
  declare -a config_dirs=(
  "${HOME}/.config/dmscripts/config"
  "/etc/dmscripts/config"
  )
  for conf in "${config_dirs[@]}"; do
    if [[ -f ${conf} ]]; then
      echo "${conf}"
      loaded=1
      break
    fi
  done
  [[ ${loaded} -eq 0 ]] && echo "No config found" ; exit 1
}

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"
# Defining our config location

# Picking a subreddit from the above subreddit_list.
# As this is loaded from other file it is technically not defined
# shellcheck disable=SC2154
subreddit=$(printf '%s\n' "${subreddit_list[@]}" | dmenu -i -l 20 -p "Choose a subreddit:" "$@") || exit

# Show the last 20 posts (titles and ids) from the chosen subreddit.
post_title=$(bash reddio print -f '$num. $title $id$nl' -l 20 "$subreddit" | \
dmenu -i -l 20 -p 'Last 20 posts on '"$subreddit" "$@")

# Display contents of chosen post in a zenity text box.
post_id=$(printf '%s\n' "$post_title" | awk '{print $NF}')
bash reddio print -f ' TITLE: $title$nl SUBMITTED: $created_pretty$nl AUTHOR: $author$nl$nl$text' by_id/"$post_id" | \
zenity --text-info --height=600 --width=600 || exit

