#!/usr/bin/env bash

# script name: dm-usbmount
# Description: mount/unmount usb drives using dmenu. No fancy daemon required
# Dependencies : dmenu, udisks2
# Author: Murtaza Udaipurwala

help(){
    printf "dm-usbmount [options]\n
    -h\tDisplays this help menu
    -m\tMount usb drive
    -u\tUnmount usb drive\n
    Drives are mounted at /run/media\n"
}

driveCount(){
    count="$(echo "$1" | wc -l)"
}

mountAll(){
    while IFS= read -r drive
    do
        udisksctl mount -b "${drive%% *}"
    done < <(printf '%s\n' "$mountable")
}

unmountAll(){
    while IFS= read -r drive
    do
        udisksctl unmount -b "$drive"
    done < <(printf '%s\n' "$mounted")
}

mount(){
    mountable="$(lsblk -lp | awk '/^\/dev\/sd.*part $/ { print $1 " ("$4")" }')"
    [ "$mountable" = "" ] && exit

    driveCount "$mountable"
    [ "$count" = "1" ] && options="$mountable" || options="$mountable\nall"

    chosen="$(printf "$options" | dmenu -i -p "Drive to mount?")" || exit
    [ "$chosen" = "all" ] && mountAll || udisksctl mount -b "${chosen%% *}"
}

unmount(){
    mounted="$(lsblk -lp | awk '/run/ { print $1 }')"
    [ "$mounted" = "" ] && exit

    driveCount "$mounted"
    [ "$count" = "1" ] && options="$mounted" || options="$mounted\nall"

    chosen="$(printf "$options" | dmenu -i -p "Drive to unmount?")"
    [ "$chosen" = "all" ] && unmountAll || udisksctl unmount -b "$chosen"
}

while getopts "hmu" arg 2>/dev/null; do
    case "${arg}" in
        h) help ;;
        m) mount ;;
        u) unmount ;;
        *) echo "invalid option\nType dm-usbmount -h for help" ;;
    esac
done
