#!/usr/bin/env bash
#
# Script name: dmsearch
# Description: Search various search engines (inspired by surfraw).
# Dependencies: dmenu and brave
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Ali Furkan Yıldız
#               HostGrady
#               Simon Ingelsson

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

function get_config() {
  local loaded=0
  declare -a config_dirs=(
  "${HOME}/.config/dmscripts/config"
  "/etc/dmscripts/config"
  )
  for conf in "${config_dirs[@]}"; do
    if [[ -f ${conf} ]]; then
      echo "${conf}"
      loaded=1
      break
    fi
  done
  [[ ${loaded} -eq 0 ]] && echo "No config found" ; exit 1
}

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

# As this is loaded from other file it is technically not defined
# shellcheck disable=SC2154 # Choosing  a search engine by name from array above.
engine=$(printf '%s\n' "${!search_options[@]}" | sort | dmenu -i -l 20 -p 'Choose search engine:') "$@" || exit

# Getting the url of the search engine we chose.
url="${search_options["${engine}"]}"

# Searching the chosen engine.
query=$(echo "$engine" | dmenu -p 'Enter search query:')

# Display search results in web browser
${DMBROWSER} "${url}${query}"
