#!/usr/bin/env bash
#
# Script name: dm-youtube
# Description: Youtube subscription manager without API access
# Dependencies: dmenu, curl, a browser (brave by default)
# Gitlab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: HostGrady

# pipefail setup
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
  # Sorts the array and lets you select a channel with dmenu
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154
  choice=$(printf '%s\n' "${!youtube_channels[@]}" | sort | dmenu -i -l 20 -p 'Select Channel:' "$@")
  # get channel id to ge able to get rss
  channel_id=$(curl -s -f -L "${youtube_channels[${choice}]}" | grep -o "channel_id=.*" | sed 's/".*//g' | awk -F"=" '{print $2}')
  _feed_url="https://www.youtube.com/feeds/videos.xml?channel_id=${channel_id}"

  video_select=$(parse_rss "$(curl -s "${_feed_url}")")
  choice=$(printf '%s\n' "${video_select}" | sort | dmenu -i -l 20 -p 'Select Video' "$@")
  video_id=$(echo "${choice}" | awk '{print $1}')

  if [[ -n ${video_id} ]]; then
    # After the respective video is chosen, run it in your web browser
    # shellcheck disable=SC2154
    $youtube_browser "https://www.youtube.com/watch?v=${video_id}"
  fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
