#!/usr/bin/env bash
#
# Script name: dmcolors
# Description: Copy a color to your clipboard using dmenu, change the colors if needed
# Dependencies: dmenu, xclip
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: sloopy3333
#               Simon Ingelsson
#               HostGrady

# Set with the flags "-e", "-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

function get_config() {
  local loaded=0
  declare -a config_dirs=(
  "${HOME}/.config/dmscripts/config"
  "/etc/dmscripts/config"
  )
  for conf in "${config_dirs[@]}"; do
    if [[ -f ${conf} ]]; then
      echo "${conf}"
      loaded=1
      break
    fi
  done
  [[ ${loaded} -eq 0 ]] && echo "No config found" ; exit 1
}

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

# As this is loaded from other file it is technically not defined
# shellcheck disable=SC2154
selected="$(printf '%s\n' "${!colors[@]}" | dmenu -p "color:")"
[ -z "${selected}" ] && exit
echo "${colors["${selected}"]}" | xclip -r -selection clipboard

