#!/usr/bin/env bash
#
# Script name: dmsounds
# Description: Choose a ambient background sound to play
# Dependencies: dmenu, ffmpeg
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#
# Need some ambient sound files?  Here are is a collection
# of 15 free to use sounds for personal or commercial projects:
# http://pbblogassets.s3.amazonaws.com/uploads/2016/09/15-Free-Ambient-Sound-Effects.zip

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

function get_config() {
  local loaded=0
  declare -a config_dirs=(
  "${HOME}/.config/dmscripts/config"
  "/etc/dmscripts/config"
  )
  for conf in "${config_dirs[@]}"; do
    if [[ -f ${conf} ]]; then
      echo "${conf}"
      loaded=1
      break
    fi
  done
  [[ ${loaded} -eq 0 ]] && echo "No config found" ; exit 1
}

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"


# shellcheck disable=SC1090
# Produces a listing of the sound files.
# As this is loaded from other file it is technically not defined
# shellcheck disable=SC2154
soundFiles=$(/bin/ls -1 "$soundDir" | grep -E ".mp3|.m4a|.ogg")

# An array of options to choose.
declare -a options=(
  "Choose sound file"
  "Play random sound"
  "Stop sound player"
  "Quit"
)

# An array of sound files to choose.
declare -a soundList=$soundFiles

# Piping the options array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -p 'Ambient sounds:' "${@}")

if [ "$choice" == "Choose sound file" ]; then
  # Piping the soundList array into dmenu.
  # We use "printf '%s\n'" to format the array one item to a line.
  choice=$(printf '%s\n' "${soundList[@]}" | sort | dmenu -i -l 20 -p 'Choose sound file:' "$@")
  # Kill PID saved in cache file.
  kill "$(cat "$HOME/.cache/dmsounds")" || echo "ffplay was not running."
  # Play the chosen sound file.
  ffplay -nodisp -loop 0 "$soundDir/$choice" &
  # Get PID for the above command and write to cache.
  _pid=$!
  echo "$_pid" > "$HOME/.cache/dmsounds"

elif [ "$choice" == "Play random sound" ]; then
  getRand=$(printf '%s\n' "${soundList[@]}" | shuf -n 1)
  # Kill PID saved in cache file.
  kill "$(cat "$HOME/.cache/dmsounds")" || echo "ffplay was not running."
  # Play random sound file.
  ffplay -nodisp -loop 0 "$soundDir/$getRand" &
  # Get PID for the above command and write to cache.
  _pid=$!
  echo "$_pid" > "$HOME/.cache/dmsounds"

elif [ "$choice" == "Stop sound player" ]; then
  kill "$(cat "$HOME/.cache/dmsounds")" || echo "ffplay was not running."

else
  echo "Program terminated." && exit 0
fi
