#!/usr/bin/env bash
# script name: dmwifi
# Description: Connect to wifi using dmenu
# Dependencies: dmenu, nmcli, Any Nerd Font
# Contributor: WitherCubes

set -euo pipefail

bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -p "Select Wifi  :" -l 20 | cut -d' ' -f1)
pass=$(echo "" | dmenu -p "Enter Password  :")
nmcli device wifi connect "$bssid" password "$pass"
